### ISSUE TITLE
No admin command in /meemo

### ISSUE THREAD

**Issue by sprnza** [qdm12/meemo#1]
Hi there!
It seems like the docker file is broken. Once started everything seems to be running, but there is no /meemo/admin command <s>and UI responds with 404</s>

**Comment by qdm12** [comment]
I'll have a look very soon, thanks for letting me know.
So it's just the admin command missing from the `commands.sh` file?

**Comment by sprnza** [comment]
Seems like it's not being shipped by Meemo any more (if it was earlier). I've looked at [this](https://hub.docker.com/r/jdipierro/meemo/) repo and there is no admin command as well once a container is started. Fortunately they've got the file in the repo, so adding it manually let me get started with Meemo.

**Comment by qdm12** [comment]
Indeed I did not notice that. Any idea why they stopped shipping it?

EDIT: I'll re-implement it in the Docker image now

**Comment by sprnza** [comment]
Have no idea :) Stumbled upon this project today in the morning :)

**Comment by qdm12** [comment]
Sorry it was my fault, I forgot to copy it over from the build stage image. I'm fixing it now. Thanks !

I'll close the issue with the commit.

**Comment by sprnza** [comment]
No worries, thanks for all the efforts to maintain the docker image :)

**Comment by qdm12** [comment]
Please wait a few minutes for Docker Hub to build the image. You can then:

```bash
docker pull qmcgaw/meemo
# If you are in a hurry: docker build -t qmcgaw/meemo https://github.com/qdm12/meemo.git
docker-compose stop meemo
docker-compose rm meemo
docker-compose up -d meemo
```

And the *commands.sh* script should also work.
